name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Replace with your build script if using a different package manager

      - name: Build
        run: npm run build  # Replace with your build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Path to the directory containing your built files
